### ISSUE TITLE
Update the YNH version to update the package?

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/epicyon_ynh#18]
From what I understand this pulls from git but if you do not change the versioning of the YNH package it means no update push right? The package is almost a year old in that regards. Should I try to submit a pull request for the YNH versioning change? Let me know if that's all it needs.

**Comment by alexAubin** [comment]
From what I see, this app doesnt rely on a `git clone` / `git pull`, it pins a specific commit : https://github.com/YunoHost-Apps/epicyon_ynh/blob/master/conf/app.src

So to update this app, you should edit this file + corresponding version number in the manifest

Feel free to make a PR and then we can trigger out automatic test suite ;)

**Comment by tio-trom** [comment]
Thanks. So it is pulling from a certain commit that archive? Because I do not see any releases/archives on their github repo. Should we just use the latest commit from the main? I can try to keep this one up to date from time to time if so.

**Comment by tio-trom** [comment]
I did I hope that's ok. I am not familiar with github that much, how do I change multiple files and push under 1 single pull request?
