### ISSUE TITLE
Bump to latest Epicyon?

### ISSUE THREAD

**Issue by PresGas** [YunoHost-Apps/epicyon_ynh#9]
Upstream has gotten many updates since the last commit here. Is that reflected in regular updates in yunohost proper or does it need bumped here?

Biggest change is upstream domain change to `libreserver.org`.

**Comment by PresGas** [comment]
Whoops, I may have found that the install is looking up to date:

https://github.com/YunoHost-Apps/epicyon_ynh/blob/1a8fae18909b863f27b98b7ded7b273b358327e3/scripts/install#L92

However, I don't see where the upgrade pulls...maybe it is just here?
https://github.com/YunoHost-Apps/epicyon_ynh/blob/1a8fae18909b863f27b98b7ded7b273b358327e3/scripts/upgrade#L72

If these assumptions are correct, please confirm and then feel free to close. Thanks ahead of time for the confirmation and education!

**Comment by pintman** [comment]
Long time no reaction. Is this app still maintained? @ericgaspar

**Comment by ericgaspar** [comment]
The package is using git pull to upgrade, just run the command below with `--force` option.

```
sudo yunohost app upgrade epicyon -u https://github.com/YunoHost-Apps/epicyon_ynh --force
```
